# How to use GPU

In [1]:
import torch
import torch.nn as nn

철칙!!!
- 같은 Device에 있는 Tensor끼리만 연산이 가능하다!
- GPU끼리라도 서로 다른 GPU에 있는 Tensor끼리는 연산이 불가능함

## Convert to CUDA tensor: cuda()

In [3]:
# GPU에 Tensor를 선언하는 방법
x = torch.cuda.FloatTensor(2, 2)

x

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [3]:
x = torch.FloatTensor(2, 2)

x

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]])

위 블록에서는 x가 CPU에 있는 Tensor였는데 아래 블록에서 x.cuda()를 통해 x가 'cuda:0'이라는 GPU로 넘어갔음

In [4]:
x.cuda()

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

In [5]:
# Device를 지정해서 Tensor를 넘기는 방법
d = torch.device('cuda:0')

In [6]:
x.cuda(device=d)
# .cuda()를 하게 되면 move가 아니라 복사/붙여넣기가 되는 거임

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

In [7]:
# x가 어디에 있는지 확인
x.device
# .cuda()는 복/붙이기 때문에 x는 cpu에 존재

device(type='cpu')

위에 방법은 "아재" 방법이라고 함,,ㅋㅋㅋ 아래에 .to()가 그나마 덜 아재스러운 방법이라고 함

## Convert to CUDA tensor: to()

In [8]:
x.to(device=d)

# x.to(device = torch.device('cpu'))라고 하면 cpu로 넘기는 거

tensor([[-4.4256e-10,  4.5685e-41],
        [-4.4256e-10,  4.5685e-41]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [2]:
x = torch.cuda.FloatTensor(2, 2)

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [10]:
x = x.cpu()

In [11]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

주의! 복/붙이 아니라 move(잘라내기/붙여넣기)다!!!

In [12]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [13]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], requires_grad=True)


In [14]:
linear = linear.cuda()  # linear = linear.cuda() 말고 그냥 linear.cuda()만 해도 GPU로 넘어감

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], device='cuda:0', requires_grad=True)


In [15]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], requires_grad=True)


In [16]:
d = torch.device('cuda:0')
linear = linear.to(d)   # .to()로도 보내짐

print_params(linear)

Parameter containing:
tensor([[ 0.5782,  0.4288],
        [-0.0220, -0.1614]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.6881, 0.0907], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [17]:
linear.device

AttributeError: 'Linear' object has no attribute 'device'

## Tricks

In [18]:
x = torch.cuda.FloatTensor(2, 2)

In [19]:
x.new(2, 2)
# x와 같은 타입의 Tensor면서 x와 같은 Device에 있는 새로운 Tensor를 만드는 거

tensor([[2.3694e-38, 1.2422e-01],
        [1.4013e-45, 0.0000e+00]], device='cuda:0')

In [20]:
torch.zeros_like(x)
# x와 같은 Device면서 같은 Size면서 0으로 찬 Tensor 생성

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [21]:
torch.ones_like(x)
# x와 같은 Device면서 같은 Size면서 1으로 찬 Tensor 생성

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [22]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')